<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE nasPreference [
<!ELEMENT nasPreference (version, productList, capacityList)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT productList (product+)>
<!ELEMENT product (productId, productName, productNameWithCapacity, icon,
						isWOL, isTeraStation, isCS, supportBNADT, supportWLSADT, isWSS, supportRaid, capacityType, sectorCorrection, defaultPassword,
						supportFeatureCapacity,supportRAIDInfo,supportSWShutdown,
						IPChangeTimeout, IPAndRaidChangeTimeout?, afterIPChangeWaitTime, needEnableSpecialAndAuth, 
						openShareFolderWithNetUse, canForceSetup, canChangeWorkgroup, imHereVersion?, waitRebootSec?, waitFileSendSec?, waitFormatSec?, needInstallRootfsFirst?, disableNetworkDriveMapping?, functionList, partitionList?)>
<!ELEMENT productId (#PCDATA)>
<!ELEMENT productName (#PCDATA)>
<!ELEMENT productNameWithCapacity (#PCDATA)>
<!ELEMENT icon (#PCDATA)>
<!ELEMENT isWOL (#PCDATA)>
<!ELEMENT isTeraStation (#PCDATA)>
<!ELEMENT isCS (#PCDATA)>
<!ELEMENT supportBNADT (#PCDATA)>
<!ELEMENT supportWLSADT (#PCDATA)>
<!ELEMENT isWSS (#PCDATA)>
<!ELEMENT supportRaid (#PCDATA)>
<!ELEMENT capacityType (#PCDATA)>
<!ELEMENT sectorCorrection (#PCDATA)>
<!ELEMENT defaultPassword (#PCDATA)>
<!ELEMENT supportFeatureCapacity (#PCDATA)>
<!ELEMENT supportRAIDInfo (#PCDATA)>
<!ELEMENT supportSWShutdown (#PCDATA)>
<!ELEMENT IPChangeTimeout (#PCDATA)>
<!ELEMENT IPAndRaidChangeTimeout (#PCDATA)>
<!ELEMENT afterIPChangeWaitTime (#PCDATA)>
<!ELEMENT needEnableSpecialAndAuth (#PCDATA)>
<!ELEMENT openShareFolderWithNetUse (#PCDATA)>
<!ELEMENT canForceSetup (#PCDATA)>
<!ELEMENT canChangeWorkgroup (#PCDATA)>
<!ELEMENT imHereVersion (#PCDATA)>
<!ELEMENT waitRebootSec (#PCDATA)>
<!ELEMENT waitFileSendSec (#PCDATA)>
<!ELEMENT waitFormatSec (#PCDATA)>
<!ELEMENT needInstallRootfsFirst (#PCDATA)>
<!ELEMENT disableNetworkDriveMapping (#PCDATA)>
<!ELEMENT functionList (function+)>
<!ELEMENT function EMPTY>
<!ATTLIST function name CDATA #REQUIRED>
<!ATTLIST function enable (yes | no) "no">
<!ELEMENT partitionList (partition+)>
<!ELEMENT partition EMPTY>
<!ATTLIST partition path CDATA #REQUIRED>
<!ELEMENT capacityList (capacity+)>
<!ELEMENT capacity (type, value, lowerBound, upperBound)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT lowerBound (#PCDATA)>
<!ELEMENT upperBound (#PCDATA)>
]>
<nasPreference>
  <version>1.0.7</version>
  <productList>
    <product>
      <productId>0x00000001</productId>
      <productName>HD-LAN</productName>
      <productNameWithCapacity>HD-%sLAN</productNameWithCapacity>
      <icon>hd-hlan</icon>
      <isWOL>yes</isWOL>
      <isTeraStation>no</isTeraStation>
      <isCS>no</isCS>
      <supportBNADT>no</supportBNADT>
	<supportWLSADT>no</supportWLSADT>
      <isWSS>no</isWSS>
      <supportRaid>no</supportRaid>
      <capacityType>1</capacityType>
      <sectorCorrection>0</sectorCorrection>
      <defaultPassword>
      </defaultPassword>
      <supportFeatureCapacity>no</supportFeatureCapacity>
      <supportRAIDInfo>no</supportRAIDInfo>
      <supportSWShutdown>no</supportSWShutdown>
      <IPChangeTimeout>10000</IPChangeTimeout>
      <afterIPChangeWaitTime>0</afterIPChangeWaitTime>
      <needEnableSpecialAndAuth>no</needEnableSpecialAndAuth>
      <openShareFolderWithNetUse>no</openShareFolderWithNetUse>
      <canForceSetup>no</canForceSetup>
      <canChangeWorkgroup>yes</canChangeWorkgroup>
      <functionList>
        <function name="imhere" enable="no" />
        <function name="openWeb" enable="yes" />
        <function name="changePassword" enable="no" />
        <function name="passwordProtect" enable="no" />
        <function name="setTime" enable="no" />
        <function name="checkDisk" enable="no" />
        <function name="format" enable="no" />
        <function name="supportAutoManagement" enable="no" />
        <function name="errorNotify" enable="no" />
      </functionList>
      <partitionList>
        <partition path="/mnt" />
      </partitionList>
    </product>
    <product>
      <productId>0x00000002</productId>
      <productName>HD-LAN</productName>
      <productNameWithCapacity>HD-%sLAN</productNameWithCapacity>
      <icon>hd-hlan</icon>
      <isWOL>yes</isWOL>
      <isTeraStation>no</isTeraStation>
      <isCS>no</isCS>
      <supportBNADT>no</supportBNADT>
	<supportWLSADT>no</supportWLSADT>
      <isWSS>no</isWSS>
      <supportRaid>no</supportRaid>
      <capacityType>1</capacityType>
      <sectorCorrection>0</sectorCorrection>
      <defaultPassword>
      </defaultPassword>
      <supportFeatureCapacity>no</supportFeatureCapacity>
      <supportRAIDInfo>no</supportRAIDInfo>
      <supportSWShutdown>no</supportSWShutdown>
      <IPChangeTimeout>10000</IPChangeTimeout>
      <afterIPChangeWaitTime>0</afterIPChangeWaitTime>
      <needEnableSpecialAndAuth>no</needEnableSpecialAndAuth>
      <openShareFolderWithNetUse>no</openShareFolderWithNetUse>
      <canForceSetup>no</canForceSetup>
      <canChangeWorkgroup>yes</canChangeWorkgroup>
      <functionList>
        <function name="imhere" enable="no" />
        <function name="openWeb" enable="yes" />
        <function name="changePassword" enable="no" />
        <function name="passwordProtect" enable="no" />
        <function name="setTime" enable="no" />
        <function name="checkDisk" enable="no" />
        <function name="format" enable="no" />
        <function name="supportAutoManagement" enable="no" />
        <function name="errorNotify" enable="no" />
      </functionList>
      <partitionList>
        <partition path="/mnt" />
      </partitionList>
    </product>
    <product>
      <productId>0x00000003</productId>
      <productName>HD-HLAN</productName>
      <productNameWithCapacity>HD-H%sLAN</productNameWithCapacity>
      <icon>hd-hlan</icon>
      <isWOL>yes</isWOL>
      <isTeraStation>no</isTeraStation>
      <isCS>no</isCS>
      <supportBNADT>no</supportBNADT>
	<supportWLSADT>no</supportWLSADT>
      <isWSS>no</isWSS>
      <supportRaid>no</supportRaid>
      <capacityType>1</capacityType>
      <sectorCorrection>0</sectorCorrection>
      <defaultPassword>
      </defaultPassword>
      <supportFeatureCapacity>no</supportFeatureCapacity>
      <supportRAIDInfo>no</supportRAIDInfo>
      <supportSWShutdown>no</supportSWShutdown>
      <IPChangeTimeout>10000</IPChangeTimeout>
      <afterIPChangeWaitTime>0</afterIPChangeWaitTime>
      <needEnableSpecialAndAuth>no</needEnableSpecialAndAuth>
      <openShareFolderWithNetUse>no</openShareFolderWithNetUse>
      <canForceSetup>no</canForceSetup>
      <canChangeWorkgroup>yes</canChangeWorkgroup>
      <functionList>
        <function name="imhere" enable="no" />
        <function name="openWeb" enable="yes" />
        <function name="changePassword" enable="no" />
        <function name="passwordProtect" enable="no" />
        <function name="setTime" enable="no" />
        <function name="checkDisk" enable="no" />
        <function name="format" enable="no" />
        <function name="supportAutoManagement" enable="no" />
        <function name="errorNotify" enable="no" />
      </functionList>
      <partitionList>
        <partition path="/mnt" />
        <partition path="/mnt2/usbdisk1" />
      </partitionList>
    </product>
    <product>
      <productId>0x00000004</productId>
      <productName>HD-HGLAN</productName>
      <productNameWithCapacity>HD-HG%sLAN</productNameWithCapacity>
      <icon>hd-hlan</icon>
      <isWOL>yes</isWOL>
      <isTeraStation>no</isTeraStation>
      <isCS>no</isCS>
      <supportBNADT>no</supportBNADT>
	<supportWLSADT>no</supportWLSADT>
      <isWSS>no</isWSS>
      <supportRaid>no</supportRaid>
      <capacityType>1</capacityType>
      <sectorCorrection>0</sectorCorrection>
      <defaultPassword>
      </defaultPassword>
      <supportFeatureCapacity>no</supportFeatureCapacity>
      <supportRAIDInfo>no</supportRAIDInfo>
      <supportSWShutdown>no</supportSWShutdown>
      <IPChangeTimeout>10000</IPChangeTimeout>
      <afterIPChangeWaitTime>0</afterIPChangeWaitTime>
      <needEnableSpecialAndAuth>no</needEnableSpecialAndAuth>
      <openShareFolderWithNetUse>no</openShareFolderWithNetUse>
      <canForceSetup>no</canForceSetup>
      <canChangeWorkgroup>yes</canChangeWorkgroup>
      <functionList>
        <function name="imhere" enable="no" />
        <function name="openWeb" enable="yes" />
        <function name="changePassword" enable="no" />
        <function name="passwordProtect" enable="no" />
        <function name="setTime" enable="no" />
        <function name="checkDisk" enable="no" />
        <function name="format" enable="no" />
        <function name="supportAutoManagement" enable="no" />
        <function name="errorNotify" enable="no" />
      </functionList>
      <partitionList>
        <partition path="/mnt" />
        <partition path="/mnt2/usbdisk1" />
      </partitionList>
    </product>
    <product>
      <productId>0x00000005</productId>
      <productName>HD-LAN</productName>
      <productNameWithCapacity>HD-%sLAN</productNameWithCapacity>
      <icon>hd-hlan</icon>
      <isWOL>yes</isWOL>
      <isTeraStation>no</isTeraStation>
      <isCS>no</isCS>
      <supportBNADT>no</supportBNADT>
	<supportWLSADT>no</supportWLSADT>
      <isWSS>no</isWSS>
      <supportRaid>no</supportRaid>
      <capacityType>1</capacityType>
      <sectorCorrection>0</sectorCorrection>
      <defaultPassword>
      </defaultPassword>
      <supportFeatureCapacity>no</supportFeatureCapacity>
      <supportRAIDInfo>no</supportRAIDInfo>
      <supportSWShutdown>no</supportSWShutdown>
      <IPChangeTimeout>10000</IPChangeTimeout>
      <afterIPChangeWaitTime>0</afterIPChangeWaitTime>
      <needEnableSpecialAndAuth>no</needEnableSpecialAndAuth>
      <openShareFolderWithNetUse>no</openShareFolderWithNetUse>
      <canForceSetup>no</canForceSetup>
      <canChangeWorkgroup>yes</canChangeWorkgroup>
      <functionList>
        <function name="imhere" enable="no" />
        <function name="openWeb" enable="yes" />
        <function name="changePassword" enable="no" />
        <function name="passwordProtect" enable="no" />
        <function name="setTime" enable="no" />
        <function name="checkDisk" enable="no" />
        <function name="format" enable="no" />
        <function name="supportAutoManagement" enable="no" />
        <function name="errorNotify" enable="no" />
      </functionList>
      <partitionList>
        <partition path="/mnt/hda" />
      </partitionList>
    </product>
    <product>
      <productId>0x00000006</productId>
      <productName>HD-HLAN</productName>
      <productNameWithCapacity>HD-H%sLAN</productNameWithCapacity>
      <icon>hd-hlan</icon>
      <isWOL>yes</isWOL>
      <isTeraStation>no</isTeraStation>
      <isCS>no</isCS>
      <supportBNADT>no</supportBNADT>
	<supportWLSADT>no</supportWLSADT>
      <isWSS>no</isWSS>
      <supportRaid>no</supportRaid>
      <capacityType>1</capacityType>
      <sectorCorrection>0</sectorCorrection>
      <defaultPassword>
      </defaultPassword>
      <supportFeatureCapacity>no</supportFeatureCapacity>
      <supportRAIDInfo>no</supportRAIDInfo>
      <supportSWShutdown>no</supportSWShutdown>
      <IPChangeTimeout>10000</IPChangeTimeout>
      <afterIPChangeWaitTime>0</afterIPChangeWaitTime>
      <needEnableSpecialAndAuth>no</needEnableSpecialAndAuth>
      <openShareFolderWithNetUse>no</openShareFolderWithNetUse>
      <canForceSetup>no</canForceSetup>
      <canChangeWorkgroup>yes</canChangeWorkgroup>
      <functionList>
        <function name="imhere" enable="no" />
        <function name="openWeb" enable="yes" />
        <function name="changePassword" enable="no" />
        <function name="passwordProtect" enable="no" />
        <function name="setTime" enable="no" />
        <function name="checkDisk" enable="no" />
        <function name="format" enable="no" />
        <function name="supportAutoManagement" enable="no" />
        <function name="errorNotify" enable="no" />
      </functionList>
      <partitionList>
        <partition path="/mnt/hda" />
        <partition path="/mnt/usbdisk1" />
      </partitionList>
    </product>
    <product>
      <productId>0x00000007</productId>
      <productName>HD-HLWG</productName>
      <productNameWithCapacity>HD-H%sLWG</productNameWithCapacity>
      <icon>hd-hlan</icon>
      <isWOL>yes</isWOL>
      <isTeraStation>no</isTeraStation>
      <isCS>no</isCS>
      <supportBNADT>no</supportBNADT>
	<supportWLSADT>no</supportWLSADT>
      <isWSS>no</isWSS>
      <supportRaid>no</supportRaid>
      <capacityType>1</capacityType>
      <sectorCorrection>0</sectorCorrection>
      <defaultPassword>
      </defaultPassword>
      <supportFeatureCapacity>no</supportFeatureCapacity>
      <supportRAIDInfo>no</supportRAIDInfo>
      <supportSWShutdown>no</supportSWShutdown>
      <IPChangeTimeout>10000</IPChangeTimeout>
      <afterIPChangeWaitTime>0</afterIPChangeWaitTime>
      <needEnableSpecialAndAuth>no</needEnableSpecialAndAuth>
      <openShareFolderWithNetUse>no</openShareFolderWithNetUse>
      <canForceSetup>no</canForceSetup>
      <canChangeWorkgroup>yes</canChangeWorkgroup>
      <functionList>
        <function name="imhere" enable="no" />
        <function name="openWeb" enable="yes" />
        <function name="changePassword" enable="no" />
        <function name="passwordProtect" enable="no" />
        <function name="setTime" enable="no" />
        <function name="checkDisk" enable="no" />
        <function name="format" enable="no" />
        <function name="supportAutoManagement" enable="no" />
        <function name="errorNotify" enable="no" />
      </functionList>
      <partitionList>
        <partition path="/mnt/hda" />
        <partition path="/mnt/usbdisk1" />
      </partitionList>
    </product>
    <product>
      <productId>0x00000008</productId>
      <productName>HS-DGL</productName>
      <productNameWithCapacity>HS-D%sGL</productNameWithCapacity>
      <icon>hs-dgl</icon>
      <isWOL>yes</isWOL>
      <isTeraStation>no</isTeraStation>
      <isCS>no</isCS>
      <supportBNADT>no</supportBNADT>
	<supportWLSADT>no</supportWLSADT>
      <isWSS>no</isWSS>
      <supportRaid>no</supportRaid>
      <capacityType>1</capacityType>
      <sectorCorrection>0</sectorCorrection>
      <defaultPassword>
      </defaultPassword>
      <supportFeatureCapacity>no</supportFeatureCapacity>
      <supportRAIDInfo>no</supportRAIDInfo>
      <supportSWShutdown>no</supportSWShutdown>
      <IPChangeTimeout>10000</IPChangeTimeout>
      <afterIPChangeWaitTime>0</afterIPChangeWaitTime>
      <needEnableSpecialAndAuth>no</needEnableSpecialAndAuth>
      <openShareFolderWithNetUse>no</openShareFolderWithNetUse>
      <canForceSetup>no</canForceSetup>
      <canChangeWorkgroup>yes</canChangeWorkgroup>
      <functionList>
        <function name="imhere" enable="no" />
        <function name="openWeb" enable="yes" />
        <function name="changePassword" enable="no" />
        <function name="passwordProtect" enable="no" />
        <function name="setTime" enable="no" />
        <function name="checkDisk" enable="no" />
        <function name="format" enable="no" />
        <function name="supportAutoManagement" enable="no" />
        <function name="errorNotify" enable="no" />
      </functionList>
      <partitionList>
        <partition path="/mnt" />
        <partition path="/mnt2/usbdisk1" />
      </partitionList>
    </product>
    <product>
      <productId>0x00000009</productId>
      <productName>LS-GL</productName>
      <productNameWithCapacity>LS-%sGL</productNameWithCapacity>
      <icon>ls-gl</icon>
      <isWOL>yes</isWOL>
      <isTeraStation>no</isTeraStation>
      <isCS>no</isCS>
      <supportBNADT>no</supportBNADT>
	<supportWLSADT>no</supportWLSADT>
      <isWSS>no</isWSS>
      <supportRaid>no</supportRaid>
      <capacityType>1</capacityType>
      <sectorCorrection>2</sectorCorrection>
      <defaultPassword>password</defaultPassword>
      <supportFeatureCapacity>no</supportFeatureCapacity>
      <supportRAIDInfo>no</supportRAIDInfo>
      <supportSWShutdown>no</supportSWShutdown>
      <IPChangeTimeout>80000</IPChangeTimeout>
      <afterIPChangeWaitTime>0</afterIPChangeWaitTime>
      <needEnableSpecialAndAuth>yes</needEnableSpecialAndAuth>
      <openShareFolderWithNetUse>no</openShareFolderWithNetUse>
      <canForceSetup>no</canForceSetup>
      <canChangeWorkgroup>yes</canChangeWorkgroup>
      <imHereVersion>2</imHereVersion>
      <waitRebootSec>240</waitRebootSec>
      <waitFormatSec>180</waitFormatSec>
      <functionList>
        <function name="imhere" enable="yes" />
        <function name="openWeb" enable="yes" />
        <function name="changePassword" enable="no" />
        <function name="passwordProtect" enable="no" />
        <function name="setTime" enable="no" />
        <function name="checkDisk" enable="no" />
        <function name="format" enable="no" />
        <function name="supportAutoManagement" enable="no" />
        <function name="errorNotify" enable="no" />
      </functionList>
      <partitionList>
        <partition path="/mnt/disk1" />
        <partition path="/mnt/usbdisk1" />
        <partition path="/mnt/usbdisk2" />
      </partitionList>
    </product>
    <product>
      <productId>0x0000000A</productId>
      <productName>HS-DHGL</productName>
      <productNameWithCapacity>HS-DH%sGL</productNameWithCapacity>
      <icon>hs-dhgl</icon>
      <isWOL>yes</isWOL>
      <isTeraStation>no</isTeraStation>
      <isCS>no</isCS>
      <supportBNADT>no</supportBNADT>
	<supportWLSADT>no</supportWLSADT>
      <isWSS>no</isWSS>
      <supportRaid>no</supportRaid>
      <capacityType>1</capacityType>
      <sectorCorrection>1</sectorCorrection>
      <defaultPassword>password</defaultPassword>
      <supportFeatureCapacity>no</supportFeatureCapacity>
      <supportRAIDInfo>no</supportRAIDInfo>
      <supportSWShutdown>no</supportSWShutdown>
      <IPChangeTimeout>80000</IPChangeTimeout>
      <afterIPChangeWaitTime>0</afterIPChangeWaitTime>
      <needEnableSpecialAndAuth>yes</needEnableSpecialAndAuth>
      <openShareFolderWithNetUse>no</openShareFolderWithNetUse>
      <canForceSetup>no</canForceSetup>
      <canChangeWorkgroup>yes</canChangeWorkgroup>
      <imHereVersion>2</imHereVersion>
      <waitRebootSec>300</waitRebootSec>
      <waitFormatSec>180</waitFormatSec>
      <needInstallRootfsFirst>yes</needInstallRootfsFirst>
      <functionList>
        <function name="imhere" enable="yes" />
        <function name="openWeb" enable="yes" />
        <function name="changePassword" enable="no" />
        <function name="passwordProtect" enable="no" />
        <function name="setTime" enable="no" />
        <function name="checkDisk" enable="no" />
        <function name="format" enable="no" />
        <function name="supportAutoManagement" enable="no" />
        <function name="errorNotify" enable="no" />
      </functionList>
      <partitionList>
        <partition path="/mnt/disk1" />
        <partition path="/mnt/usbdisk1" />
        <partition path="/mnt/usbdisk2" />
      </partitionList>
    </product>
    <product>
      <productId>0x0000000B</productId>
      <productName>LS-LGL</productName>
      <productNameWithCapacity>LS-L%sGL</productNameWithCapacity>
      <icon>ls-lgl</icon>
      <isWOL>yes</isWOL>
      <isTeraStation>no</isTeraStation>
      <isCS>no</isCS>
      <supportBNADT>no</supportBNADT>
	<supportWLSADT>no</supportWLSADT>
      <isWSS>no</isWSS>
      <supportRaid>no</supportRaid>
      <capacityType>5</capacityType>
      <sectorCorrection>1</sectorCorrection>
      <defaultPassword>
      </defaultPassword>
      <supportFeatureCapacity>no</supportFeatureCapacity>
      <supportRAIDInfo>no</supportRAIDInfo>
      <supportSWShutdown>no</supportSWShutdown>
      <IPChangeTimeout>40000</IPChangeTimeout>
      <afterIPChangeWaitTime>0</afterIPChangeWaitTime>
      <needEnableSpecialAndAuth>yes</needEnableSpecialAndAuth>
      <openShareFolderWithNetUse>yes</openShareFolderWithNetUse>
      <canForceSetup>yes</canForceSetup>
      <canChangeWorkgroup>no</canChangeWorkgroup>
      <waitRebootSec>240</waitRebootSec>
      <waitFileSendSec>1200</waitFileSendSec>
      <waitFormatSec>600</waitFormatSec>
      <functionList>
        <function name="imhere" enable="no" />
        <function name="openWeb" enable="no" />
        <function name="changePassword" enable="yes" />
        <function name="passwordProtect" enable="yes" />
        <function name="setTime" enable="yes" />
        <function name="checkDisk" enable="yes" />
        <function name="format" enable="yes" />
        <function name="supportAutoManagement" enable="yes" />
        <function name="errorNotify" enable="yes" />
      </functionList>
      <partitionList>
        <partition path="/mnt/disk1" />
      </partitionList>
    </product>
    <product>
      <productId>0x0000000E</productId>
      <productName>LS-HGL</productName>
      <productNameWithCapacity>LS-H%sGL</productNameWithCapacity>
      <icon>ls-hgl</icon>
      <isWOL>yes</isWOL>
      <isTeraStation>no</isTeraStation>
      <isCS>no</isCS>
      <supportBNADT>no</supportBNADT>
	<supportWLSADT>no</supportWLSADT>
      <isWSS>no</isWSS>
      <supportRaid>no</supportRaid>
      <capacityType>4</capacityType>
      <sectorCorrection>1</sectorCorrection>
      <defaultPassword>password</defaultPassword>
      <supportFeatureCapacity>no</supportFeatureCapacity>
      <supportRAIDInfo>no</supportRAIDInfo>
      <supportSWShutdown>no</supportSWShutdown>
      <IPChangeTimeout>40000</IPChangeTimeout>
      <afterIPChangeWaitTime>0</afterIPChangeWaitTime>
      <needEnableSpecialAndAuth>yes</needEnableSpecialAndAuth>
      <openShareFolderWithNetUse>no</openShareFolderWithNetUse>
      <canForceSetup>no</canForceSetup>
      <canChangeWorkgroup>yes</canChangeWorkgroup>
      <waitRebootSec>200</waitRebootSec>
      <waitFormatSec>500</waitFormatSec>
      <functionList>
        <function name="imhere" enable="no" />
        <function name="openWeb" enable="yes" />
        <function name="changePassword" enable="no" />
        <function name="passwordProtect" enable="no" />
        <function name="setTime" enable="no" />
        <function name="checkDisk" enable="no" />
        <function name="format" enable="no" />
        <function name="supportAutoManagement" enable="yes" />
        <function name="errorNotify" enable="yes" />
      </functionList>
      <partitionList>
        <partition path="/mnt/disk1" />
        <partition path="/mnt/usbdisk1" />
      </partitionList>
    </product>
    <product>
      <productId>0x0000000F</productId>
      <productName>LS-CL</productName>
      <productNameWithCapacity>LS-C%sL</productNameWithCapacity>
      <icon>ls-cl</icon>
      <isWOL>yes</isWOL>
      <isTeraStation>no</isTeraStation>
      <isCS>no</isCS>
      <supportBNADT>no</supportBNADT>
	<supportWLSADT>no</supportWLSADT>
      <isWSS>no</isWSS>
      <supportRaid>no</supportRaid>
      <capacityType>4</capacityType>
      <sectorCorrection>1</sectorCorrection>
      <defaultPassword>password</defaultPassword>
      <supportFeatureCapacity>no</supportFeatureCapacity>
      <supportRAIDInfo>no</supportRAIDInfo>
      <supportSWShutdown>no</supportSWShutdown>
      <IPChangeTimeout>40000</IPChangeTimeout>
      <afterIPChangeWaitTime>0</afterIPChangeWaitTime>
      <needEnableSpecialAndAuth>yes</needEnableSpecialAndAuth>
      <openShareFolderWithNetUse>no</openShareFolderWithNetUse>
      <canForceSetup>no</canForceSetup>
      <canChangeWorkgroup>yes</canChangeWorkgroup>
      <waitRebootSec>480</waitRebootSec>
      <waitFormatSec>500</waitFormatSec>
      <functionList>
        <function name="imhere" enable="no" />
        <function name="openWeb" enable="yes" />
        <function name="changePassword" enable="no" />
        <function name="passwordProtect" enable="no" />
        <function name="setTime" enable="no" />
        <function name="checkDisk" enable="no" />
        <function name="format" enable="no" />
        <function name="supportAutoManagement" enable="yes" />
        <function name="errorNotify" enable="yes" />
      </functionList>
      <partitionList>
        <partition path="/mnt/disk1" />
        <partition path="/mnt/usbdisk1" />
      </partitionList>
    </product>
    <product>
      <productId>0x00000010</productId>
      <productName>LS-CHL</productName>
      <productNameWithCapacity>LS-CH%sL</productNameWithCapacity>
      <icon>ls-chl</icon>
      <isWOL>yes</isWOL>
      <isTeraStation>no</isTeraStation>
      <isCS>no</isCS>
      <supportBNADT>no</supportBNADT>
	<supportWLSADT>no</supportWLSADT>
      <isWSS>no</isWSS>
      <supportRaid>no</supportRaid>
      <capacityType>4</capacityType>
      <sectorCorrection>1</sectorCorrection>
      <defaultPassword>password</defaultPassword>
      <supportFeatureCapacity>no</supportFeatureCapacity>
      <supportRAIDInfo>no</supportRAIDInfo>
      <supportSWShutdown>no</supportSWShutdown>
      <IPChangeTimeout>40000</IPChangeTimeout>
      <afterIPChangeWaitTime>0</afterIPChangeWaitTime>
      <needEnableSpecialAndAuth>yes</needEnableSpecialAndAuth>
      <openShareFolderWithNetUse>no</openShareFolderWithNetUse>
      <canForceSetup>no</canForceSetup>
      <canChangeWorkgroup>yes</canChangeWorkgroup>
      <waitRebootSec>480</waitRebootSec>
      <waitFormatSec>500</waitFormatSec>
      <functionList>
        <function name="imhere" enable="no" />
        <function name="openWeb" enable="yes" />
        <function name="changePassword" enable="no" />
        <function name="passwordProtect" enable="no" />
        <function name="setTime" enable="no" />
        <function name="checkDisk" enable="no" />
        <function name="format" enable="no" />
        <function name="supportAutoManagement" enable="yes" />
        <function name="errorNotify" enable="yes" />
      </functionList>
      <partitionList>
        <partition path="/mnt/disk1" />
        <partition path="/mnt/usbdisk1" />
      </partitionList>
    </product>
    <product>
      <productId>0x00000011</productId>
      <productName>LS-XHL</productName>
      <productNameWithCapacity>LS-XH%sL</productNameWithCapacity>
      <icon>ls-cl</icon>
      <isWOL>yes</isWOL>
      <isTeraStation>no</isTeraStation>
      <isCS>no</isCS>
      <supportBNADT>no</supportBNADT>
	<supportWLSADT>no</supportWLSADT>
      <isWSS>no</isWSS>
      <supportRaid>no</supportRaid>
      <capacityType>4</capacityType>
      <sectorCorrection>1</sectorCorrection>
      <defaultPassword>password</defaultPassword>
      <supportFeatureCapacity>no</supportFeatureCapacity>
      <supportRAIDInfo>no</supportRAIDInfo>
      <supportSWShutdown>no</supportSWShutdown>
      <IPChangeTimeout>40000</IPChangeTimeout>
      <afterIPChangeWaitTime>0</afterIPChangeWaitTime>
      <needEnableSpecialAndAuth>yes</needEnableSpecialAndAuth>
      <openShareFolderWithNetUse>no</openShareFolderWithNetUse>
      <canForceSetup>no</canForceSetup>
      <canChangeWorkgroup>yes</canChangeWorkgroup>
      <waitRebootSec>480</waitRebootSec>
      <waitFormatSec>500</waitFormatSec>
      <functionList>
        <function name="imhere" enable="no" />
        <function name="openWeb" enable="yes" />
        <function name="changePassword" enable="no" />
        <function name="passwordProtect" enable="no" />
        <function name="setTime" enable="no" />
        <function name="checkDisk" enable="no" />
        <function name="format" enable="no" />
        <function name="supportAutoManagement" enable="yes" />
        <function name="errorNotify" enable="yes" />
      </functionList>
      <partitionList>
        <partition path="/mnt/disk1" />
        <partition path="/mnt/usbdisk1" />
      </partitionList>
    </product>
    <product>
      <productId>0x00000012</productId>
      <productName>LS-CHL-V2</productName>
      <productNameWithCapacity>LS-CH%sL-V2</productNameWithCapacity>
      <icon>ls-cl</icon>
      <isWOL>yes</isWOL>
      <isTeraStation>no</isTeraStation>
      <isCS>no</isCS>
      <supportBNADT>no</supportBNADT>
	<supportWLSADT>no</supportWLSADT>
      <isWSS>no</isWSS>
      <supportRaid>no</supportRaid>
      <capacityType>4</capacityType>
      <sectorCorrection>1</sectorCorrection>
      <defaultPassword>password</defaultPassword>
      <supportFeatureCapacity>no</supportFeatureCapacity>
      <supportRAIDInfo>no</supportRAIDInfo>
      <supportSWShutdown>no</supportSWShutdown>
      <IPChangeTimeout>40000</IPChangeTimeout>
      <afterIPChangeWaitTime>0</afterIPChangeWaitTime>
      <needEnableSpecialAndAuth>yes</needEnableSpecialAndAuth>
      <openShareFolderWithNetUse>no</openShareFolderWithNetUse>
      <canForceSetup>no</canForceSetup>
      <canChangeWorkgroup>yes</canChangeWorkgroup>
      <waitRebootSec>480</waitRebootSec>
      <waitFormatSec>500</waitFormatSec>
      <functionList>
        <function name="imhere" enable="no" />
        <function name="openWeb" enable="yes" />
        <function name="changePassword" enable="no" />
        <function name="passwordProtect" enable="no" />
        <function name="setTime" enable="no" />
        <function name="checkDisk" enable="no" />
        <function name="format" enable="no" />
        <function name="supportAutoManagement" enable="yes" />
        <function name="errorNotify" enable="yes" />
      </functionList>
      <partitionList>
        <partition path="/mnt/disk1" />
        <partition path="/mnt/usbdisk1" />
      </partitionList>
    </product>
    <product>
      <productId>0x00000013</productId>
      <productName>LS-SL</productName>
      <productNameWithCapacity>LS-S%sL</productNameWithCapacity>
      <icon>ls-sl</icon>
      <isWOL>yes</isWOL>
      <isTeraStation>no</isTeraStation>
      <isCS>no</isCS>